### ISSUE TITLE
[5.7] Make some core packages optional

### ISSUE THREAD

**Issue by zorca** [laravel-zero/laravel-zero#130]
Good day! First I want to say thank you very much for the excellent framework, I use it now to create a console application. Is it possible to move all noncritical dependencies from the framework to the application skeleton? Like: "nunomaduro/laravel-console-menu":"1.0.*" . Console menu not working on Windows due to the fact that POSIX will not install on Windows. And it would be nice to make the option of choosing these dependencies in final app. I am also using symfony/filesystem instead of league/flysystem because I need the absolute path to the file.

**Comment by nunomaduro** [comment]
@zorca Did you tried using the bash thing on windows?

**Comment by zorca** [comment]
The problem is not in bash. I can't even install a framework without errors on Windows.
```
D:\Projects>composer create-project --prefer-dist laravel-zero/laravel-zero ox
Installing laravel-zero/laravel-zero (v5.6.2)
  - Installing laravel-zero/laravel-zero (v5.6.2): Loading from cache
Created project in ox
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-zero/framework v5.6.0 requires nunomaduro/laravel-console-menu 1.0.* -> satisfiable by nunomaduro/laravel-console-menu[v1.0.0, v1.0.1].
    - laravel-zero/framework v5.6.1 requires nunomaduro/laravel-console-menu 1.0.* -> satisfiable by nunomaduro/laravel-console-menu[v1.0.0, v1.0.1].
    - laravel-zero/framework v5.6.2 requires nunomaduro/laravel-console-menu 1.0.* -> satisfiable by nunomaduro/laravel-console-menu[v1.0.0, v1.0.1].
    - nunomaduro/laravel-console-menu v1.0.0 requires php-school/cli-menu 2.1.* -> satisfiable by php-school/cli-menu[2.1.0].
    - nunomaduro/laravel-console-menu v1.0.1 requires php-school/cli-menu 2.1.* -> satisfiable by php-school/cli-menu[2.1.0].
    - php-school/cli-menu 2.1.0 requires ext-posix * -> the requested PHP extension posix is missing from your system.
    - Installation request for laravel-zero/framework 5.6.* -> satisfiable by laravel-zero/framework[v5.6.0, v5.6.1, v5.6.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\Program Files\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

D:\Projects>
```

**Comment by zorca** [comment]
But this is not the main problem. I would like the framework to be modular. If all non-critical extensions are in the kernel, it will pull a lot of unnecessary into the final package.

**Comment by nunomaduro** [comment]
I understand your point of view. But: **The framework is modular**. That's why I made the `app:install` command.

With the `app:install` command you can install optional stuff. Concerning the all the `nunomaduro/laravel*` related packages, we are talking about single file packages. They are literally  super small. They are **not** "lot of unnecessary" stuff.

Please take a look into the `composer.json` of the framework. You will see that this framework is actually super small.

**Comment by nunomaduro** [comment]
Anyway, I will take in consideration your issue for the next major version! Thanks!

**Comment by wouter2203** [comment]
It is possible to install on Windows using the composer `--ignore-platform-reqs` flag, but I think it should be possible to install it without that (ugly) flag.

I had to do some debugging and googling to even get it installed and that shouldn't be the case for such a cool project :)

**Comment by zorca** [comment]
I agree. Not all work only on Mac and Ubuntu. I used to work in the Windows console and I love it. I want to build the app in the Windows console. At the moment I had to give up Laravel Zero for this reason. I just did the same structure, it's not that complicated. It took half a day.

**Comment by nunomaduro** [comment]
@wouter2203 @zorca I will take a look on this issue this weekend! 👍

**Comment by wouter2203** [comment]
The problem is that "php-school/cli-menu" does not support Windows.

I don't know how exactly this can be solved, as "laravel-console-menu" (understandable) requires this package.

Composer, as far as I know, has no possibility to install a package if it is supported and otherwise skip it (without using the `--ignore-plateform-reqs` flag).

If you know a solution to this, you could check if the package has been installed and there is TTY support then just open the menu. If it is not supported, you can show a list of the options with an index infront of it and ask via `$this->ask()` which index the user wants. That way you can provide support (in a less appealing way, but hey, it'll work) for Windows.

**Comment by nunomaduro** [comment]
That would be a breaking change, since the $this->menu() returns an instance of `NunoMaduro\LaravelConsoleMenu::class`.

Laravel Zero's versioning scheme maintains the following convention: `paradigm.minor.patch`.

I am trying not to release a minor release just because of this.

**Comment by wouter2203** [comment]
That could still be the case, this is just an idea (haven't made it, so not sure if this is practical, could do some testing this weekend):

Make an interface and have `Menu::class` implement it.

This way we can create multiple implementations of the interface. One for Windows and one for Mac/Linux.

As far as I can see most of the functions do not need editing, they just set variables containing background color etc.

Only the open function should be different, whereas on Mac/Linux it can do what it does now. And on Windows we change the function to the following:

```php
    public function open()
    {
        $this->table(...); // The options

        return $this->ask('What option do you want?');
    }
```

This still wouldn't solve the `composer install` problem, since `php-school/cli-menu` still require `posix` the be enabled. Which isn't possible on Windows.

Again, this is just an idea. Haven't tested it. And this still doesn't solve the first problem which `php-school/cli-menu` introduces.

**Comment by nunomaduro** [comment]
@zorca @wouter2203  Just made a patch on Laravel Zero to make it work on Windows. Do you mind of creating a fresh project and test it?

**Comment by wouter2203** [comment]
Sure, will do tomorrow!

**Comment by wouter2203** [comment]
I'm sorry 'tomorrow' took me so long :-(!

I was able to run `composer install` without any issues!

**Comment by zorca** [comment]
`composer install`  works well

**Comment by nunomaduro** [comment]
The Windows issue has been solved. Concerning the comment "Making some packages optional": There is no sense. We are talking about packages of **one class** - Those features are in separated packages just because I may want to use those features on Laravel itself.

**The framework is already modular** . That's why we can install illuminate components optionally.
