### ISSUE TITLE
Is possible get .env vars?

### ISSUE THREAD

**Issue by abkrim** [laravel-zero/laravel-zero#137]
Hi.

I try to access .env vars with Laravel Zero.

Create a config/myconf.php

```<?php

return [
    'cuentica_token' => env('CUENTICA_TOKEN', 'fail')
];
```

On my own .env file
```
CUENTICA_TOKEN='This_is_OK'
```

Code for test

```
dd(config('cuentica'));
```

Show 
```
fail
```

I need put token on config file for work.

Best regards.

**Comment by nunomaduro** [comment]
@abkrim You need to install the .env component. Check the docs: http://laravel-zero.com/#/usage?id=environment-configuration

**Comment by abkrim** [comment]
oops.. sory. I apoligze for despite.

A lot of thanks for this & for your package.

**Comment by nroussis** [comment]
Hello, Excuse my naiveness. After I have made some changes in the env files I see that have not been applied. I suspect some kind of config cache? Can I clear it since commands php artisan cache:clear and php artisan config:clear are not there?.. Thank you for the great laravel version! Zero is exactly what I need.
