### ISSUE TITLE
Building app not supported on Windows

### ISSUE THREAD

**Issue by zecipriano** [laravel-zero/laravel-zero#175]
When building an app on Windows with `app:build` the process fails.

The main issue, I assume, is that `humbug/box` [does not support Windows ](https://github.com/humbug/box/issues/193) yet.

Another issue is the way `box` is called from `BuildCommand.php`. Right now is called the unix way `./box` but from Windows it needs to be called `php box`. Although there's no point in fixing this until `box` supports Windows.

Maybe, for now, mention in the documentation that building on Windows is not possible.

---

This is the output I get when running the equivalent box command directly on the command line. The error says something like "The syntax for the file name, directory name, or volume label is incorrect."

![box_command](https://user-images.githubusercontent.com/430800/49666069-c5ef7d80-fa4e-11e8-8871-7531094ed5e2.png)

**Comment by nunomaduro** [comment]
@zecipriano If you use bash in Windows it works right?

**Comment by zecipriano** [comment]
@nunomaduro Yes, when using the linux subsystem thing, it works. 

Except that, when I run `app:build` I hit a 60 seconds timeout, but that's another issue. When I increase that timeout, it works fine.

**Comment by nunomaduro** [comment]
@zecipriano Can you re-test this with Laravel Zero 5.8?

**Comment by nunomaduro** [comment]
@zecipriano Can you re-test this with Laravel Zero 5.8?

**Comment by zecipriano** [comment]
@nunomaduro The issue persists. Same output as the screenshot in the first message.

**Comment by paKanhu** [comment]
@nunomaduro This issue is related to [https://github.com/laravel/framework/issues/28344](https://github.com/laravel/framework/issues/28344). I tried by following below process and it worked.

1. `composer create-project --prefer-dist --no-scripts laravel-zero/laravel-zero movie-cli`
2. `cd movie-cli`
3. `composer config repositories.illuminate/config '{"type": "git", "url": "https://github.com/illuminate/config"}'`
4. `composer require illuminate/config:5.8.9`
5. `php application app:rename`

**Comment by mengfanyin** [comment]
![bug](https://user-images.githubusercontent.com/16729739/56858319-76343300-69aa-11e9-8957-5ec6b8e2e671.png)

I encountered some problems as shown in the figure above when i ran `php application app:build`.

**Comment by arnoldkunihira** [comment]
Was this solved, because I have a similar situation below using laravel-zero framework 6.0 on windows using gitbash?

*Stack trace is below*
1. Moving application to production mode: ✔
   2. Compile into a single file: ✔


   ErrorException  : rename(C:\wamp64\www\user_mgt_console\user_console.phar,C:\wamp64\www\user_mgt_console\builds\user_console): The system cannot find the file specified. (code: 2)

  at C:\wamp64\www\user_mgt_console\vendor\illuminate\filesystem\Filesystem.php:238
    234|      * @return bool
    235|      */
    236|     public function move($path, $target)
    237|     {
  > 238|         return rename($path, $target);
    239|     }
    240|
    241|     /**
    242|      * Copy a file to a new location.

  Exception trace:

  1   rename("C:\wamp64\www\user_mgt_console\user_console.phar", "C:\wamp64\www\user_mgt_console\builds\user_console")
      C:\wamp64\www\user_mgt_console\vendor\illuminate\filesystem\Filesystem.php:238

  2   Illuminate\Filesystem\Filesystem::move("C:\wamp64\www\user_mgt_console\user_console.phar", "C:\wamp64\www\user_mgt_console\builds\user_console")
      C:\wamp64\www\user_mgt_console\vendor\illuminate\support\Facades\Facade.php:239

  Please use the argument -v to see more details.

**Comment by stevebauman** [comment]
@arnoldkunihira No this was not solved. The underlying .phar compiler ([box](https://github.com/humbug/box)) does not support Windows - as mentioned by the OP.

**Comment by arnoldkunihira** [comment]
So any solutions yet @stevebauman since the compiler does not support windows?

**Comment by stevebauman** [comment]
Unfortunately right now the only solution I have is pretty archaic:

1. Include the entire `vendor` folder of your project (after running `composer install -o --no-dev`) in my GitHub repository (you'll need to remove the `/vendor` entry from the `.gitignore` file)
2. Download an entire ZIP of the GitHub repo using the "Clone or Download" button
3. Extracting the ZIP onto the server where you want the application stored

Not anywhere nearly as nice as a compiled `.phar` file, but I don't have time at the moment to wrestle with them. I haven't found any that support Windows.

**Comment by owenvoke** [comment]
This should be resolved in v7.0.0, at least partially as Box still doesn't officially support Windows.

**Comment by nunomaduro** [comment]
if this problem still persist on 7.0.0 please create an new issue.
