### ISSUE TITLE
Command option default value not recognized?

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#202]
I am curious, does LZ not support the extended option default value as used by Artisan commands?  If I use the following in an Artisan Command, the same syntax is not honored by LZ?

```
    protected $signature = 'command
                                {name : xxx} 
                                {--f|fname=mike : Include first name}
```

When running the command, the value retrieved by `$this->option('fname')` in the handle method returns `null`  

```
> command xxx --fname
```
but
```
> command xxx --fname mike
```
the `fname` value of `mike` will be returned

However, if I use the same signature in an Artisan command, the value returned will be `mike`

In there a consicous decision to not support option default values, or is this a "bug" 🐞

**Comment by nunomaduro** [comment]
We are using the the `illuminate/console` package, so everything that works on Artisan commands should work here.

You mean that that feature works on Laravel, but not on Laravel Zero?

**Comment by mikeerickson** [comment]
Yes, that is what I am saying?  I figured you were using ‘Illuminate/console` thus I found it to be strange

**Comment by linuxjuggler** [comment]
Basically, there are no problems at all, the execution of the command is incorrect.

when you execute:

```
 command xxx --fname
```

you specify the next thing to `--fname` which is `null` here as the value for `--fname` that's why you get `null`

Meanwhile here
```
command xxx --fname mike
```
you are setting the value to `mike`.

**you should not use `--fname` unless you want to set a different value than the default one**

but for more better validation you should check the value in your `handle` function and ask the user to provide a value if the value for `--fname` was null.

**Comment by mikeerickson** [comment]
@linuxjuggler Thank you for clarification on this, I am not sure why I was expecting something different.  After going back and trying to reproduce with standard Laravel commands, I was not able to even make my OP break.

@nunomaduro Sorry for the noise
