### ISSUE TITLE
bug 6.0: builds don't discover commands within app/Commands

### ISSUE THREAD

**Issue by nunomaduro** [laravel-zero/laravel-zero#243]
How to reproduce:

1. `php application app:build`
2. None of the commands within `app\Commands` are on the list of the built file.

**Comment by pxgamer** [comment]
I think this might be due to the change to [Illuminate\Foundation\Console\Kernel at Line 236](https://github.com/laravel-zero/foundation/blame/bc63b7ba83dcbeaf7a8b11c9c09f2ce6d23b8bce/src/Illuminate/Foundation/Console/Kernel.php#L236).

Reverting this change so that it doesn't use `realpath()` seems to resolve the issue. But, I'll need to test this more thoroughly. :+1:
