### ISSUE TITLE
Laravel-Zero + Eloquent And Other current Laravel Stuff

### ISSUE THREAD

**Issue by allanfreitas** [laravel-zero/laravel-zero#25]
Hi,

We can add to the dependencies and use things like Eloquent?
Will be needed something extra or only add the dependency and de config/database.php file?

**Comment by nunomaduro** [comment]
Hey @allanfreitas,

I would like to use this issue in order to start a discussion with developers that like Laravel Zero. I hope you don't mind. 😏

Your question is actually a question that surrounds Laravel Zero and it will directly effect next releases of this project. 🤔

Laravel Zero was build to be the most **simple and minimalist** as possible, and that's why he includes only 3 main **Laravel components**:

- [illuminate/config](https://github.com/laravel/framework/tree/5.4/src/Illuminate/Config)
- [illuminate/console](https://github.com/laravel/framework/tree/5.4/src/Illuminate/Console)
- [illuminate/container](https://github.com/laravel/framework/tree/5.4/src/Illuminate/Container)

Using [Laravel Eloquent](https://github.com/laravel/framework/tree/5.4/src/Illuminate/Database) is not be a problem, normally you include the package via composer, then you add the database section on the configuration file and you **should be good** 👍 Actually my next demo application will be an example of that!

Concerning other packages, like community packages I think some of them could fail, the reason why is because their **dependencies are not clearly defined**.

To be honest, I am trying to avoid the scenario of including the package [illuminate/framework](https://github.com/laravel/framework) in order to not include unnecessary packages in this context ,like [illuminate/view](https://github.com/laravel/framework/tree/5.4/src/Illuminate/View).

I would love to ear more opinions about this subject. 🤓

**Comment by allanfreitas** [comment]
@nunomaduro I think the same way.

The console with Database Support it's very helpful, If not included on the core, but with a easy *extra package* to do this integration like **laravel-zero/eloquent**.

I work with many clients, and I'm using the [climate](http://climate.thephpleague.com/) from phpleague :)And setup the connection by hand its a waste of my time :).

A Laravel Standalone Cli with Database(or even the Eloquent) it's a handy tool :)

**Comment by deleugpn** [comment]
I know next-to-nothing about Laravel Zero, but I came from Twitter to give my 2 cents.

Have you considered making a database:install command? When issuing it on a clean installation, you throw an exception saying `composer require `illuminate/database` (Eloquent) by identifying that the package is not installed (perhaps trying to instantiate Capsule?).

After the user has manually required the dependency (clearly opting-in for it), `database:install` would scaffold any configuration necessary to start using Eloquent on the package.

**Comment by nunomaduro** [comment]
@deleugpn Actually I find your idea super interesting! 😏

**Comment by ivanPrunier** [comment]
@deleugn That would actually be super cool!

**Comment by introwit** [comment]
So it would work with a file based database, or the config file would have the credentials and we would setup a PDO connection between a MySQL, etc. database and work with it? @allanfreitas how do you see it?

**Comment by allanfreitas** [comment]
@introwit , today I need to create a basic connection and execute my queries :)
With the proposal of @deleugpn , I think it's a good start point.

Something like this will be great too:

#The **component** command
`php application component:install `

- with no Args List the components current avaliable for install
- with arg like database|cache|queue *(some packages will not be easy, but these 3 are essential)*
- The command can:
  - check if the desired illuminate/{package} is on the composer.json under the dependencies key;
  - create the proper config file like "database.php or cache.php";
  - create the need integration file for the package chosen

I think on this way, like Lumen is the API Microframework For Laravel,
Laravel-Zero could become the better Laravel Based **CLI Framework** 🥇 

@nunomaduro My other 2 cents :)

**Comment by introwit** [comment]
Database component makes sense for now. Not sure about others though. Thank you for putting the time into it @allanfreitas & @deleugpn , much appreciated ❤️

**Comment by nunomaduro** [comment]
Thank you all for putting time/cents 😂 into this discussing. I really appreciate your help.

Preparing a release for this #LaraconEU easy install of database component as main feature.

The release of the new version will also close the thread. ✅

**Comment by allanfreitas** [comment]
I'm avaliable to help with coding to :) Or other cents if you want, you can reach me on twitter, or by email, I've already sent you a email from my email right now :)

https://twitter.com/allanfreitas

**Comment by nunomaduro** [comment]
Hey @allanfreitas, I just made a silence release of Laravel Zero 3.3.

Normally php application component:install should response to your problem. Can you check ?

**Comment by allanfreitas** [comment]
@nunomaduro , Sure, I will check it tomorrow, I need to parse some client data :),
And after I will give the feedback here.

**Comment by allanfreitas** [comment]
@nunomaduro , how I can use this **silence release**, I've not found the Tag 3.3 :)

**Comment by nunomaduro** [comment]
@allanfreitas Please perform:

1. `composer clear`
2. `composer create-project --prefer-dist nunomaduro/laravel-zero your-app-name`

**Comment by allanfreitas** [comment]
![image](https://user-images.githubusercontent.com/304086/29796824-b802c8e2-8c29-11e7-99ee-935620b7618b.png)
Working Awesome!!!!!

Just Used:
```php
$sql = 'MYSQL STRING';

$result = DB::select($sql);

//And other terminal stuff to mount the table
```

**Comment by introwit** [comment]
@allanfreitas thank you so much Allan :)

**Comment by nunomaduro** [comment]
@allanfreitas Thank you so much for that beautiful feedback! Really glad that you like it ☺️

**Comment by Razmatez** [comment]
Is there a way to run the `migrate` command after the illuminate\database package is installed?

e.g `php todo migrate`

**Comment by nunomaduro** [comment]
@Razmatez I will check it tonight 😎

**Comment by nunomaduro** [comment]
@Razmatez Hey buddy. No time today for checking your issue. Tomorrow night I will take a look.

**Comment by Razmatez** [comment]
Thanks. Whenever you have time 😊

**Comment by nunomaduro** [comment]
Hey @Razmatez. I made a small POC today. Do you mind of validate it? Instructions:

> 1. composer create-project laravel-zero/laravel-zero application dev-hotfix-3.7.1
> 2. cd application 
> 3. php application component:install illuminate/database
> 4. php application list

This should list all `migrate` related commands of Laravel.

If all is good, I will perform a small refacto and than include this on the next version.

**Comment by Razmatez** [comment]
I have tested, it is working as expected ☺

[image: Inline image 1]

**Comment by nunomaduro** [comment]
@Razmatez The next release of Laravel Version have now migrations! Check the changelog & enjoy!
