### ISSUE TITLE
chore: start preparing next version of laravel zero 7

### ISSUE THREAD

**Issue by nunomaduro** [laravel-zero/laravel-zero#254]
@pxgamer Do you think you can start work on this? I have collision, larastan ready for laravel 7.

**Comment by pxgamer** [comment]
Would definitely be good to take a look. I'll be back with a PC on Sunday and I should be able to get started!

**Comment by nunomaduro** [comment]
Thanks! Enjoy your vacations!

**Comment by owenvoke** [comment]
There is an issue with Symfony Process that needs to be resolved.

With the [`ComposerContract`](https://github.com/laravel-zero/framework/blob/7.x/src/Providers/Composer/Composer.php) we allow providing a string (i.e. `illuminate/log "^7.0"`) to the [`require()`](https://github.com/laravel-zero/framework/blob/7.x/src/Providers/Composer/Composer.php#L67-L70) method. However, due to changes in the Symfony Process component, the space with quotes causes it to be a double-quoted argument. Which fails with Composer stating:
```txt
[UnexpectedValueException]                                        
  Could not parse version constraint ": Invalid version string """
```
On Windows, you get the following as the actual command it attempts to run:
```cmd
composer require "padraic/phar-updater """^^"1.0.6""" "" C:\Users\owen.voke\projects\laravel-zero"
```

**Comment by nunomaduro** [comment]
@owenvoke No problem, let's create an issue and to address it.

**Comment by owenvoke** [comment]
## Component checklist

- [x] Console Dusk
- [ ] Database
- [x] DotEnv
- [ ] Log
- [ ] Logo
- [ ] Menu
- [ ] Queue
- [x] Schedule List
- [ ] Self Update

**Comment by innoflash** [comment]
cant wait for its update

**Comment by owenvoke** [comment]
Forgot to close this, so closing now. 👍
