### ISSUE TITLE
error after build

### ISSUE THREAD

**Issue by sajjad-ser** [laravel-zero/laravel-zero#257]
hi when i build my app and run it result is this error:
```
PHP Warning:  require_once(phar:///home/sajjad/projects/bot/builds/sajjad/bootstrap/app.php): failed to open stream: phar error: "bootstrap/app.php" is not a file in phar "/home/sajjad/projects/bot/builds/sajjad" in phar:///home/sajjad/projects/bot/builds/sajjad/bot on line 19
PHP Fatal error:  require_once(): Failed opening required 'phar:///home/sajjad/projects/bot/builds/sajjad/bootstrap/app.php' (include_path='.:/usr/share/php') in phar:///home/sajjad/projects/bot/builds/sajjad/bot on line 19
```

**Comment by pxgamer** [comment]
Hi @sajjad-ser, could you confirm the contents of your `box.json` includes the `bootstrap` directory in the directories key?

I've tested this and was unable to replicate the issue, could you provide some more details such as the version of Laravel Zero so we can investigate this. 👍

**Comment by sajjad-ser** [comment]
wow my box.json is empty 
sorry

**Comment by pxgamer** [comment]
No worries, any further problems feel free to ask. :ok_hand:

**Comment by Gummibeer** [comment]
I had the same issue after I've canceled a build with `CTRL+C`. It seems like the build scripts rewrites the `box.json` - because it's also "uglified" if it was prettified before.
Is there any reason to do so?

**Comment by owenvoke** [comment]
@Gummibeer, it looks like this was changed as part of laravel-zero/framework@8dec2adb06526c051fd2a86cc5a3b5a2fcb99045, the `main` key is added to the `box.json`. I'm not sure if the Box builds would work without this? However, I'm pretty sure I've seen notices when building Laravel Zero apps that mention that it's already set to the default. 🤔

If you're on Mac/Linux (with PCNTL), since v6.1.0 of Laravel Zero, the Box configuration _should_ be set back to what it was originally (https://github.com/laravel-zero/framework/pull/365) when pressing `CTRL+C`. Unless something weird happened.

**Comment by phuclh** [comment]
@owenvoke @Gummibeer I already revert the box.json content but still facing this issue, do you know how to fix it, thank you.
