### ISSUE TITLE
Create a command - Incorrect namespace

### ISSUE THREAD

**Issue by gravataLonga** [laravel-zero/laravel-zero#288]
Hello i find an issue related with `laravel-zero/foundation` (i think the source of evil). I don't know if  make correction on the `foundation` repo or in `framework` repo.  

The problem is when a try to create a new command, it's generated with the wrong `use` statement.  

If you can see this line of code:  
https://github.com/laravel-zero/foundation/blob/master/src/Illuminate/Foundation/Console/stubs/console.stub#L5  

It's complete different to this one, which is correct one:  
https://github.com/laravel-zero/laravel-zero/blob/master/app/Commands/InspiringCommand.php#L6  

```use LaravelZero\Framework\Commands\Command;``` this is correct because in order to use the [schedule feature](https://github.com/laravel-zero/laravel-zero/blob/master/app/Commands/InspiringCommand.php#L40-L43) the class must extend from `LaravelZero`. 

I'm more than happy to make a change, i've already make test on `framework` but the problem is more deep on rabbit hole.  

![Screenshot 2020-04-22 at 00 02 19](https://user-images.githubusercontent.com/1126525/79922977-8e5b5880-842c-11ea-8ef0-038febf80f8a.png)

Please give some direction where i can make a pull request. ;)  

Thank in advance.

**Comment by owenvoke** [comment]
Hi @gravataLonga, it looks like the [`StubPublishCommand`](https://github.com/laravel-zero/framework/blob/f76b8cf12a6ca54ebbb27bab5d64a2db43f3b80c/src/Commands/StubPublishCommand.php) should publish the stubs [from here](https://github.com/laravel-zero/framework/tree/f76b8cf12a6ca54ebbb27bab5d64a2db43f3b80c/src/Commands/stubs) which does include the right class. 🤔 This does seem to be working as expected when you publish the stubs.

However, in https://github.com/laravel-zero/framework/commit/9c314e1df22c3b8122cf1e10a52c1f4bb8f23892, the `getStub()` method was removed which means that it falls back to the base command which is the issue because now it is using the `__DIR__` path from the `laravel-zero/foundation` directory.

We should be able to basically just add a PR to the framework that adds:
```php
    /** {@inheritdoc} */
    protected function getStub(): string
    {
        $relativePath = '/stubs/console.stub';

        return file_exists($customPath = $this->laravel->basePath(trim($relativePath, '/')))
            ? $customPath
            : __DIR__.$relativePath;
    }
```

**Comment by gravataLonga** [comment]
You can make PR I don’t mind. And credit for 😂😅 Only want to this to work.. 

Side note, IMHO must be a test for this.
