### ISSUE TITLE
Use Laravel Zero with custom framework

### ISSUE THREAD

**Issue by pavrip** [laravel-zero/laravel-zero#297]
I am building a custom framework for a university project,
Similar to artisan in Laravel, I want to use it to help do a lot of the tasks like make modules, components, and database migrations,

I am already using composer, autoload but there are no dependencies as I am using core extensions for everything except mail,

Is there a way I can create a Laravel zero project and then combine it to my web framework?

**Comment by owenvoke** [comment]
Hi @pavrip, that's an interesting question. 🤔 I guess Laravel Zero would be possible although it might be a bit awkward.

I'm not really sure what the best way to do this would be though.

**Comment by yoramdelangen** [comment]
Yes there is a way. I build a Laravel Zero project besides my "backend" portion/logic of the entire application. Why? Because the application will run on-premise and we don't have access or control over it.
By creating the Laravel Zero project we can compress and encrypt the build and use the binary within the backend. We have a set of API endpoints that are filtering and mapping all the input information and send it via a process to the binary. 

In that case we can have a licence security layer on top of our (business logic) commands and API will handle it as a Forbidden (in case of licence fail).

@pavrip why would you want to have layer within a command-line build?

**Comment by pavrip** [comment]
Well I am building a DDD framework for a University project and I want to have a nice command line application tool that I can use similar to Symfony and Laravel.

Now I was thinking of using the Symfony one because it comes with the maker component where I can create my own make:mycustommakethinggy

So I might go for that
________________________________
