### ISSUE TITLE
Laravel Cache Facade

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#87]
Not sure if this is possible, but is there a way to utilize the Laravel cache facade?

**Comment by ilesinge** [comment]
Yes it is !

- Require Illuminate/Cache in your project : "composer require illuminate/cache"
- Put a cache.php file in the config folder with the following code (other config options are possible if you want to use another driver or change the cache location for instance):
```php
<?php

return [
    'default' => 'file',

    'stores' => [
        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],
    ],
];
```
- In your command, add the following use statement:
```php
use Illuminate\Support\Facades\Cache;
```
- And I guess, go cache all the things !
```php
    public function handle(): void
    {
        $slow_result = Cache::rememberForever('my_slow_method', function() {
            sleep(1);
            return "I'm slow";
        });
        $this->info($slow_result);
    }
```

**Comment by ilesinge** [comment]
In fact it seems that Illuminate/Cache is already included, so you can skip the first step (composer require)

**Comment by nunomaduro** [comment]
Hey @MelonSmasher! Check @ilesinge solution and give us feedback! 👍

Thanks @ilesinge for the solution ❤️

**Comment by MelonSmasher** [comment]
@ilesinge @nunomaduro Thanks guys, works perfectly!

**Comment by EthraZa** [comment]
Or the default app installation is missing cache.php file or the Docs are missing this example. 
I'm searching this for hours already. I'm new to Laravel, Laravel Zero is been my entrypoint so I don't have where to look for a cache.php example within my own projects.

**Comment by owenvoke** [comment]
@EthraZa, this currently isn't in the docs. But perhaps it'd be worth it being added. By default, as mentioned above, it uses the `array` driver (see [the `CacheServiceProvider`](https://github.com/laravel-zero/framework/blob/2c4988ef262101f29bff58936a67b95a738b50b9/src/Providers/Cache/CacheServiceProvider.php#L40)).

As the cache service provider is installed by default, we can probably just mention a bit on adding the above to a `config/cache.php` because a component installer would be a bit unnecessary. You can basically copy the contents of the above code into your `config/cache.php` file.

**Comment by EthraZa** [comment]
Yes, I copied it and it worked great. 
The problem was the Google was not showing this to me, I had to came to GitHub and search for the issues with no filter to find it. It could be in the docs yes or, since the component is already installed, just add a cache.php file to explicit put the defaults, the same way the log component do, would be cool.

**Comment by owenvoke** [comment]
Just about to add a docs entry.  I think we purposefully don't include the `cache.php` file to keep the config directory clean for most applications.
